# Generated by Django 3.1.1 on 2020-09-16 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('follower_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower_of', 'followed_by')},
            },
        ),
    ]
