# Generated by Django 3.1.1 on 2020-09-17 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200917_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
