# Generated by Django 3.1.1 on 2020-09-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200929_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by_current_user',
            field=models.BooleanField(default=False),
        ),
    ]
